export const UPDATE_CONFERENCE = 'UPDATE_CONFERENCE'

export const ADD_LOG = 'ADD_LOG'
export const CLEAR_LOG = 'CLEAR_LOG'

export const ADD_PARTICIPANT = 'ADD_PARTICIPANT'

export const DELETE_ALL_PARTICIPANTS = 'DELETE_ALL_PARTICIPANTS'
export const DELETE_PARTICIPANT_BY_CHANNEL = 'DELETE_PARTICIPANT_BY_CHANNEL'
export const DELETE_PARTICIPANT_BY_CALLERID = 'DELETE_PARTICIPANT_BY_CALLERID'

export const UPDATE_PARTICIPANT_BY_CHANNEL = 'UPDATE_PARTICIPANT_BY_CHANNEL'
export const UPDATE_PARTICIPANT_BY_CALLERID = 'UPDATE_PARTICIPANT_BY_CALLERID'
export const UPDATE_ALL_PARTICIPANTS = 'UPDATE_ALL_PARTICIPANTS'

export const UPDATE_LABELS = 'UPDATE_LABELS'
export const UPDATE_URLS = 'UPDATE_URLS'
export const UPDATE_CURRENT_PARTICIPANT = 'UPDATE_CURRENT_PARTICIPANT'
export const UPDATE_FLASH = 'UPDATE_FLASH'

